//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.Nhap_Kho {
    
    
    public partial class Nhap_Kho_Management {
        
        /// <summary>
        /// uc4002_Nhap_Kho_Management control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TKS_Thuc_Tap_Web.Nhap_Kho.UserControl.uc1718_Nhap_Kho_Management uc4002_Nhap_Kho_Management;
    }
}
