//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.Danh_Muc {
    
    
    public partial class Loai_San_Pham {
        
        /// <summary>
        /// uc3002_Loai_San_Pham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TKS_Thuc_Tap_Web.Danh_Muc.UserControl.uc3002_Loai_San_Pham uc3002_Loai_San_Pham;
    }
}
